dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -e .

script:
  - python -m unittest discover -s "qozyd" -p "*.py" -t .

notifications:
  email:
    - checks@qozy.io
